# Generated by Django 3.2 on 2021-05-02 09:28

from django.db import migrations, models
import django.db.models.deletion
import roadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(validators=[roadmap.models.validate_deadline_not_in_past]),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.goal')),
            ],
        ),
    ]
